// PM2 process manager config for production VPS deployment
// NestJS apps run from compiled dist/main.js
// tsx apps (voicebot, tts, analytics) run via globally installed tsx
// Usage: pm2 start ecosystem.config.js
module.exports = {
  apps: [
    {
      name: "gateway",
      cwd: "/opt/callcloser/apps/gateway",
      script: "node",
      args: "dist/main.js",
      env_file: "/opt/callcloser/.env",
      max_memory_restart: "512M",
      restart_delay: 3000,
      watch: false,
    },
    {
      name: "crm-service",
      cwd: "/opt/callcloser/apps/crm-service",
      script: "node",
      args: "dist/main.js",
      env_file: "/opt/callcloser/.env",
      max_memory_restart: "512M",
      restart_delay: 3000,
      watch: false,
    },
    {
      name: "calls-service",
      cwd: "/opt/callcloser/apps/calls-service",
      script: "node",
      args: "dist/main.js",
      env_file: "/opt/callcloser/.env",
      max_memory_restart: "512M",
      restart_delay: 3000,
      watch: false,
    },
    {
      name: "prompt-service",
      cwd: "/opt/callcloser/apps/prompt-service",
      script: "node",
      args: "dist/main.js",
      env_file: "/opt/callcloser/.env",
      max_memory_restart: "256M",
      restart_delay: 3000,
      watch: false,
    },
    {
      name: "tts-service",
      cwd: "/opt/callcloser/apps/tts-service",
      script: "tsx",
      args: "src/index.ts",
      env_file: "/opt/callcloser/.env",
      max_memory_restart: "256M",
      restart_delay: 3000,
      watch: false,
    },
    {
      name: "voicebot",
      cwd: "/opt/callcloser/apps/voicebot",
      script: "tsx",
      args: "src/index.ts",
      env_file: "/opt/callcloser/.env",
      max_memory_restart: "512M",
      restart_delay: 5000,
      watch: false,
    },
    {
      name: "analytics-worker",
      cwd: "/opt/callcloser/apps/analytics-worker",
      script: "tsx",
      args: "src/main.ts",
      env_file: "/opt/callcloser/.env",
      max_memory_restart: "256M",
      restart_delay: 3000,
      watch: false,
    },
    {
      name: "web",
      cwd: "/opt/callcloser/apps/web",
      script: "node",
      args: "node_modules/.bin/next start -p 3000",
      env_file: "/opt/callcloser/.env",
      env: { PORT: "3000", NODE_ENV: "production" },
      max_memory_restart: "512M",
      restart_delay: 3000,
      watch: false,
    },
  ],
};
